package org.starloco.locos.enums;

public enum InteractiveObjects {
    FRENE(1),
    SCIE(2),
    CHENE(8),
    TABLE_DE_CONFECTION(11),
    ATELIER(12),
    ETABLI(13),
    CHAUDRON(15),
    ZAAP(16),
    FER(17),
    FOUR(22),
    ARGENT(24),
    OR(25),
    PIERRE_DE_BAUXITE(26),
    MOULE(27),
    IF(28),
    EBENE(29),
    ORME(30),
    ERABLE(31),
    CHARME(32),
    CHATAIGNIER(33),
    NOYER(34),
    MERISIER(35),
    PIERRE_DE_KOBALTE(37),
    BLE(38),
    HOUBLON(39),
    MOULIN(40),
    MEULE(41),
    LIN(42),
    ORGE(43),
    SEIGLE(44),
    AVOINE(45),
    CHANVRE(46),
    MALT(47),
    TAS_DE_PATATES(48),
    TABLE_A_PATATES(49),
    CONCASSEUR(50),
    ETAIN(52),
    PIERRE_CUIVREE(53),
    MANGANESE(54),
    BRONZE(55),
    SOURCE_DE_JOUVENCE(56),
    ENCLUME(57),
    MACHINE_A_COUDRE(58),
    MARMITE(60),
    EDELWEISS(61),
    ALEMBIC(62),
    FROMENT(63),
    EPEAUTRE(64),
    SORGHO(65),
    MENTHE_SAUVAGE(66),
    TREFLE_A_5_FEUILLES(67),
    ORCHIDEE_FREYESQUE(68),
    MORTIER_ET_PILON(69),
    PORTE(70),
    PETITS_POISSONS_MER(71),
    SOMOON_AGRESSIF(72),
    PWOULPE(73),
    POISSONS_RIVIERE(74),
    PETITS_POISSONS_RIVIERE(75),
    GROS_POISSONS_RIVIERE(76),
    POISSONS_MER(77),
    GROS_POISSONS_MER(78),
    POISSONS_GEANTS_RIVIERE(79),
    TRUITE_VASEUSE(80),
    POISSONS_GEANTS_MER(81),
    COTON(82),
    FILEUSE(83),
    PUITS(84),
    COFFRE(85),
    MACHINE_A_COUDRE_2(86),
    ETABLI_EN_BOIS(88),
    ALAMBIC_2(90),
    ENCLUME_MAGIQUE(92),
    CONCASSEUR_MUNSTER(93),
    PLAN_DE_TRAVAIL(94),
    PLAN_DE_TRAVAIL_2(95),
    PLAN_DE_TRAVAIL_3(96),
    PLAN_DE_TRAVAIL_4(97),
    BOMBU(98),
    OMBRE_ETRANGE(99),
    PICHON(100),
    OLIVIOLET(101),
    MACHINE_DE_FORCE(102),
    ETABLI_PYROTECHNIQUE(103),
    KOINKOIN(104),
    POUBELLE(105),
    ZAAPI(106),
    ENCLUME_A_BOUCLIERS(107),
    BAMBOU(108),
    BAMBOU_SOMBRE(109),
    BAMBOU_SACRE(110),
    RIZ(111),
    PANDOUILLE(112),
    DOLOMITE(113),
    SILICATE(114),
    MACHINE_A_COUDRE_MAGIQUE(116),
    ATELIER_MAGIQUE(117),
    TABLE_MAGIQUE(118),
    LISTE_DES_ARTISANS(119),
    ENCLOS(120),
    KALIPTUS(121),
    ATELIER_DE_BRICOLAGE(122),
    LEVIER(127),
    STATUE_DE_CLASSE(128),
    CONCASSEUR_DE_CARTES(130),
    CONFECTIONNEUR_DE_CARTES(131),
    BOUGIE_SPECTRALE(132);

    private final int id;

    InteractiveObjects(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

    public static InteractiveObjects getById(int id) {
        for (InteractiveObjects object : values()) {
            if (object.getId() == id) {
                return object;
            }
        }
        throw new IllegalArgumentException("No InteractiveObjects found with id: " + id);
    }
}
