package org.starloco.locos.enums;

public enum Titles {
    GOULE_DE(1),
    VAMPYRE(2),
    VAMPYRE_SANGLANT(3),
    VAMPYRE_MAUDYT(4),
    VAMPYRE_ULTYME(5),
    VAMPYRE_DEMONYAQUE(6),
    VAMPYRE_RUNYQUE(7),
    POURFENDEUR_DE_BWORKER(8),
    POURFENDEUR_DU_SPHINCTER_CELL(9),
    POURFENDEUR_DU_KOULOSSE(10),
    POURFENDEUR_DU_WA_WABBIT(11),
    POURFENDEUR_DU_KIMBO(12),
    POURFENDEUR_DU_MINOTOROR(13),
    POURFENDEUR_DU_DRAGON_COCHON(14),
    POURFENDEUR_DU_CHENE_MOU(15),
    POURFENDEUR_DU_MOON(16),
    POURFENDEUR_DU_DARK_VLAD(17),
    HEROS_BICENTENAIRE(18),
    CHEVALIER_HISPANIQUE(19),
    TERREUR_DE_LA_PRESQU_ILE(20),
    DEKROKILLISEUR(21),
    BUCHERON_PRIMORDIAL(22),
    FORGEUR_D_EPEES_PRIMORDIAL(23),
    SCULPTEUR_D_ARCS_PRIMORDIAL(24),
    FORGEUR_DE_MARTEAUX_PRIMORDIAL(25),
    CORDONNIER_PRIMORDIAL(26),
    BIJOUTIER_PRIMORDIAL(27),
    FORGEUR_DE_DAGUES_PRIMORDIAL(28),
    SCULPTEUR_DE_BATONS_PRIMORDIAL(29),
    SCULPTEUR_DE_BAGUETTES_PRIMORDIAL(30),
    FORGEUR_DE_PELLES_PRIMORDIAL(31),
    MINEUR_PRIMORDIAL(32),
    BOULANGER_PRIMORDIAL(33),
    ALCHIMISTE_PRIMORDIAL(34),
    TAILLEUR_PRIMORDIAL(35),
    PAYSAN_PRIMORDIAL(36),
    FORGEUR_DE_HACHES_PRIMORDIAL(37),
    PECHEUR_PRIMORDIAL(38),
    CHASSEUR_PRIMORDIAL(39),
    FORGEMAGE_DE_DAGUES_PRIMORDIAL(40),
    FORGEMAGE_D_EPEES_PRIMORDIAL(41),
    FORGEMAGE_DE_MARTEAUX_PRIMORDIAL(42),
    FORGEMAGE_DE_PELLES_PRIMORDIAL(43),
    FORGEMAGE_DE_HACHES_PRIMORDIAL(44),
    SCULPTEMAGE_D_ARCS_PRIMORDIAL(45),
    SCULPTEMAGE_DE_BAGUETTES_PRIMORDIAL(46),
    SCULPTEMAGE_DE_BATONS_PRIMORDIAL(47),
    BOUCHER_PRIMORDIAL(48),
    POISSONNIER_PRIMORDIAL(49),
    FORGEUR_DE_BOUCLIERS_PRIMORDIAL(50),
    CORDOMAGE_PRIMORDIAL(51),
    JOAILLOMAGE_PRIMORDIAL(52),
    COSTUMAGE_PRIMORDIAL(53),
    BRICOLEUR_PRIMORDIAL(54),
    AVENTURIER_DE_L_AVENT_651(55),
    NOWELISTE(56),
    POURFENDEUR_DU_SAPIK(57),
    POURFENDEUR_DU_PAPA_NOWEL(58),
    POURFENDEUR_DU_PERE_FWETAR(59),
    PANDI_FAIT_DE_LA_RESISTANCE(60),
    GRAND_MAITRE_DES_CARTES(61),
    MAITRE_DES_CARTES(62),
    GLADIATROOLEUR_NOVICE(63),
    GLADIATROOLEUR_EXPERT(64),
    MAITRE_GLADIATROOLEUR(65),
    AVENTURIER_DE_L_AVENT_652(66),
    AVENTURIER_DE_L_AVENT_653(67),
    AVENTURIER_DE_L_AVENT_654(68),
    KROSPLAYEUR_INTEMPOREL(69),
    GRAND_MAITRE_DES_ELEMENTS(70),
    POURFENDEUR_DU_CROCABULIA(71),
    POURFENDEUR_DU_RASBOUL(72),
    POURFENDEUR_DU_RAT_NOIR_CORROMPU(73),
    POURFENDEUR_DE_L_ABRAKNYDE_ANCESTRAL(74),
    POURFENDEUR_DU_CHENE_MOU_KROLLECTOR(75),
    POURFENDEUR_DU_DRAGON_COCHON_KROLLECTOR(76),
    MELOMANE_EN_PUISSANCE(77),
    POURFENDEUR_DU_WA_WABBIT_KROLLECTOR(78),
    POURFENDEUR_DU_KOULOSSE_KROLLECTOR(79),
    POURFENDEUR_DU_SPHINCTER_CELL_KROLLECTOR(80),
    POURFENDEUR_DU_BWORKER_KROLLECTOR(81),
    A_L_ANCIENNE(85),
    POURFENDEUR_DU_TYNRIL_CONSTERNEE(86),
    POURFENDEUR_DU_TYNRIL_DECONCERTE(87),
    POURFENDEUR_DU_TYNRIL_PERFIDE(88),
    POURFENDEUR_DU_TYNRIL_AHURI(89),
    AME_SOEUR_DE(90),
    COEUR_A_PRENDRE(91),
    POURFENDEUR_DU_SCARABOSSE_DORE(92),
    POURFENDEUR_DU_TANKOUI_SAN(93),
    POURFENDEUR_DU_CORAILLEUR_MAGISTRAL(94),
    POURFENDEUR_DU_MEULOU(95),
    POURFENDEUR_DE_LA_BWORKETTE(96),
    WAKFU_S5_PRODUCER(97),
    ANKAFFILLIE(98);

    private final int id;

    Titles(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

    public static Titles getById(int id) {
        for (Titles title : values()) {
            if (title.getId() == id) {
                return title;
            }
        }
        throw new IllegalArgumentException("No Title found with id: " + id);
    }
}
